# Generated by Django 3.2.6 on 2021-08-28 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0002_auto_20210828_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dataativado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 12, 16, 20, 237621, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='usuario',
            name='datacriado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 12, 16, 20, 237621, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='usuario',
            name='datainativado',
            field=models.DateTimeField(null=True),
        ),
    ]
