# Generated by Django 3.2.6 on 2021-08-28 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0003_auto_20210828_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('estado', models.IntegerField(default=1)),
                ('datacriado', models.DateTimeField(default=datetime.datetime(2021, 8, 28, 12, 53, 15, 870617, tzinfo=utc))),
                ('dataativado', models.DateTimeField(default=datetime.datetime(2021, 8, 28, 12, 53, 15, 870617, tzinfo=utc))),
                ('datainativado', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cardapio',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataativado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 12, 53, 15, 868616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='datacriado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 12, 53, 15, 868616, tzinfo=utc)),
        ),
    ]
