# Generated by Django 3.2.6 on 2021-08-28 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0004_auto_20210828_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('fotografia', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'itemdocardapio',
            },
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='dataativado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 13, 26, 53, 762616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='datacriado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 13, 26, 53, 762616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataativado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 13, 26, 53, 761617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='datacriado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 13, 26, 53, 761617, tzinfo=utc)),
        ),
    ]
