# Generated by Django 3.2.6 on 2021-08-28 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0005_auto_20210828_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='dataativado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 6, 25, 205919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='datacriado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 6, 25, 205919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataativado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 6, 25, 204918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='datacriado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 6, 25, 204918, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CardapioItemDoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.IntegerField(default=1)),
                ('datacriado', models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 6, 25, 207920, tzinfo=utc))),
                ('dataativado', models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 6, 25, 209919, tzinfo=utc))),
                ('datainativado', models.DateTimeField(null=True)),
                ('cardapio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='divinahamburgueriaapp.cardapio')),
                ('itemdocardapio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itensdocardapio', to='divinahamburgueriaapp.itemdocardapio')),
            ],
            options={
                'db_table': 'cardapioitemdocardapio',
            },
        ),
    ]
