# Generated by Django 3.2.6 on 2021-08-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0007_auto_20210830_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='dataativado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='datacriado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardapioitemdocardapio',
            name='dataativado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardapioitemdocardapio',
            name='datacriado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidosalao',
            name='dataemitido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataativado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='datacriado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
