# Generated by Django 3.2.6 on 2021-08-31 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0008_auto_20210830_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('estado', models.IntegerField(default=1)),
                ('datacriado', models.DateTimeField(auto_now_add=True)),
                ('dataativado', models.DateTimeField(auto_now_add=True)),
                ('datainativado', models.DateTimeField(null=True)),
                ('endereco', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_fornecedores', to='divinahamburgueriaapp.endereco')),
                ('telefone', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telefones_fornecedores', to='divinahamburgueriaapp.telefone')),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
        migrations.CreateModel(
            name='ItemDoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('estoqueminimo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'itemdoestoque',
            },
        ),
        migrations.CreateModel(
            name='PedidoDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(default=1)),
                ('dataemitido', models.DateTimeField(auto_now_add=True)),
                ('datacancelado', models.DateTimeField(null=True)),
                ('dataembalado', models.DateTimeField(null=True)),
                ('dataentregue', models.DateTimeField(null=True)),
                ('observacao', models.CharField(max_length=400)),
                ('estadopagamento', models.IntegerField(default=1)),
                ('datapagamento', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'pedidodelivery',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_clientes', to='divinahamburgueriaapp.endereco'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telefones_clientes', to='divinahamburgueriaapp.telefone'),
        ),
        migrations.AlterField(
            model_name='pedidosalao',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao_clientes', to='divinahamburgueriaapp.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidosalao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao_usuarios', to='divinahamburgueriaapp.usuario'),
        ),
        migrations.CreateModel(
            name='PedidoSalaoCardapioItemDoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=400)),
                ('cardapioitemdocardapio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao_cardapiositemdocardapio', to='divinahamburgueriaapp.cardapioitemdocardapio')),
                ('pedidosalao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao', to='divinahamburgueriaapp.pedidosalao')),
            ],
            options={
                'db_table': 'pedidosalaocardapioitemdocardapio',
            },
        ),
        migrations.CreateModel(
            name='PedidoDeliveryCardapioItemDoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=400)),
                ('cardapioitemdocardapio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosdelivery_cardapiositemdocardapio', to='divinahamburgueriaapp.cardapioitemdocardapio')),
                ('pedidodelivery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosdelivery', to='divinahamburgueriaapp.pedidodelivery')),
            ],
            options={
                'db_table': 'pedidodeliverycardapioitemdocardapio',
            },
        ),
        migrations.AddField(
            model_name='pedidodelivery',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosdelivery_clientes', to='divinahamburgueriaapp.cliente'),
        ),
        migrations.AddField(
            model_name='pedidodelivery',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosdelivery_usuarios', to='divinahamburgueriaapp.usuario'),
        ),
        migrations.CreateModel(
            name='PedidoDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(default=1)),
                ('descricao', models.CharField(max_length=400)),
                ('dataemitido', models.DateTimeField(auto_now_add=True)),
                ('datacancelado', models.DateTimeField(null=True)),
                ('dataentregue', models.DateTimeField(null=True)),
                ('dataestocado', models.DateTimeField(null=True)),
                ('estadopagamento', models.IntegerField(default=1)),
                ('datapagamento', models.DateTimeField(null=True)),
                ('fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='divinahamburgueriaapp.fornecedor')),
            ],
            options={
                'db_table': 'pedidodecompra',
            },
        ),
        migrations.CreateModel(
            name='ItemDoEstoquePedidoDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField(default=1)),
                ('itemdoestoque', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itensdoestoque', to='divinahamburgueriaapp.itemdoestoque')),
                ('pedidodecompra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosdecompra', to='divinahamburgueriaapp.pedidodecompra')),
            ],
            options={
                'db_table': 'itemdoestoquepedidodecompra',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('itemdoestoque', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itensdoestoque_estocados', to='divinahamburgueriaapp.itemdoestoque')),
            ],
            options={
                'db_table': 'estoque',
            },
        ),
    ]
