# Generated by Django 3.2.6 on 2021-09-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0009_auto_20210831_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeliveryItemDoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(max_length=400)),
                ('itemdocardapio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosdelivery_itemdocardapio', to='divinahamburgueriaapp.itemdocardapio')),
            ],
            options={
                'db_table': 'pedidodeliveryitemdocardapio',
            },
        ),
        migrations.CreateModel(
            name='PedidoSalaoItemDoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(max_length=400)),
                ('itemdocardapio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao_itemdocardapio', to='divinahamburgueriaapp.itemdocardapio')),
            ],
            options={
                'db_table': 'pedidoalaoitemdocardapio',
            },
        ),
        migrations.RemoveField(
            model_name='pedidosalaocardapioitemdocardapio',
            name='cardapioitemdocardapio',
        ),
        migrations.RemoveField(
            model_name='pedidosalaocardapioitemdocardapio',
            name='pedidosalao',
        ),
        migrations.AddField(
            model_name='pedidodelivery',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidosalao',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PedidoDeliveryCardapioItemDoCardapio',
        ),
        migrations.DeleteModel(
            name='PedidoSalaoCardapioItemDoCardapio',
        ),
        migrations.AddField(
            model_name='pedidosalaoitemdocardapio',
            name='pedidosalao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao', to='divinahamburgueriaapp.pedidosalao'),
        ),
        migrations.AddField(
            model_name='pedidodeliveryitemdocardapio',
            name='pedidodelivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosdelivery', to='divinahamburgueriaapp.pedidodelivery'),
        ),
    ]
