# Generated by Django 3.2.6 on 2021-09-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0010_auto_20210906_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_clientes', to='divinahamburgueriaapp.endereco'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones_clientes', to='divinahamburgueriaapp.telefone'),
        ),
    ]
