# Generated by Django 3.2.6 on 2021-09-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0011_auto_20210906_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosalao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao_clientes', to='divinahamburgueriaapp.cliente'),
        ),
    ]
