# Generated by Django 3.2.6 on 2021-09-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0012_alter_pedidosalao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosalao',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidossalao_clientes', to='divinahamburgueriaapp.cliente'),
        ),
    ]
