# Generated by Django 3.2.6 on 2021-09-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0013_alter_pedidosalao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosalao',
            name='observacao',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosalaoitemdocardapio',
            name='observacao',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
