# Generated by Django 3.2.6 on 2021-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0015_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
