# Generated by Django 3.2.6 on 2021-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0016_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodelivery',
            name='observacao',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
