# Generated by Django 3.2.6 on 2021-09-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0018_alter_pedidodeliveryitemdocardapio_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_fornecedores', to='divinahamburgueriaapp.endereco'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones_fornecedores', to='divinahamburgueriaapp.telefone'),
        ),
    ]
