# Generated by Django 3.2.6 on 2021-10-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0019_auto_20210930_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodecompra',
            name='datacotacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodecompra',
            name='observacao',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='pedidodecompra',
            name='dataemitido',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidodecompra',
            name='estadopagamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidodelivery',
            name='estadopagamento',
            field=models.IntegerField(default=0),
        ),
    ]
