# Generated by Django 3.2.6 on 2021-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0020_auto_20211002_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodecompra',
            name='datacotacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
