# Generated by Django 3.2.6 on 2021-10-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0021_alter_pedidodecompra_datacotacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemDoEstoquePedidoDeCompra',
            new_name='PedidoDeCompraItemDoEstoque',
        ),
        migrations.RemoveField(
            model_name='pedidodecompra',
            name='descricao',
        ),
    ]
