# Generated by Django 3.2.6 on 2021-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0022_auto_20211007_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdoestoque',
            name='conteudo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemdoestoque',
            name='unidade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
