# Generated by Django 3.2.6 on 2021-10-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0023_auto_20211007_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodecompraitemdoestoque',
            name='preco',
        ),
        migrations.AddField(
            model_name='pedidodecompraitemdoestoque',
            name='precototal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidodecompraitemdoestoque',
            name='precounitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
