# Generated by Django 3.2.6 on 2021-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0024_auto_20211008_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodecompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
