# Generated by Django 3.2.6 on 2021-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0026_pedidodecompraitemdoestoque_estocado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdoestoque',
            name='estoqueminimo',
        ),
        migrations.AddField(
            model_name='itemdoestoque',
            name='marca',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
