# Generated by Django 3.2.6 on 2021-10-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0028_auto_20211015_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='dataativado',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='datainativado',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='datacriado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
