# Generated by Django 3.2.6 on 2021-10-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0032_itemdocardapio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdocardapio',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='itemdocardapio',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='itemdocardapio',
        ),
    ]
