# Generated by Django 3.2.6 on 2021-10-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divinahamburgueriaapp', '0033_auto_20211018_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdocardapio',
            name='receita',
        ),
        migrations.RemoveField(
            model_name='itemdocardapio',
            name='revenda',
        ),
        migrations.AddField(
            model_name='itemdocardapio',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receita',
            name='itemdocardapio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itensdocardapioreceita', to='divinahamburgueriaapp.itemdocardapio'),
        ),
        migrations.AddField(
            model_name='revenda',
            name='itemdocardapio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itensdocardapiorevenda', to='divinahamburgueriaapp.itemdocardapio'),
        ),
    ]
